# Generated by Django 4.2.1 on 2023-05-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('BuyerName', models.CharField(max_length=225)),
                ('Address', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('StyleCode', models.CharField(max_length=225, unique=True)),
                ('ItemName', models.CharField(blank=True, max_length=225, null=True)),
                ('Buyer', models.CharField(max_length=225)),
                ('BuyerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.buyer')),
            ],
        ),
    ]
